CREATE TABLE dim_infa_location(
	Location_key	int	Primary Key,
	[LocationID] [float] ,
	[LocationType] [nvarchar](255) ,
	[LocationDescription] [nvarchar](255) ,
	[Region] [nvarchar](255) ,
	[RegionManagerUserID] [float] ,
	[Address] [nvarchar](255) ,
	[City] [nvarchar](255) ,
	[PostalCode] [nvarchar](255) ,
	[PhoneNumber] [nvarchar](255) ,
	[Fax] [nvarchar](255) ,
	[Email] [nvarchar](255) ,
	[StoreManagerUserID] [float] ,
	[IsDelegateServiceCenter] [nvarchar](255) ,
	[Enabled] [nvarchar](255) ,
	[IsPartWareHouse] [nvarchar](255) ,
	[FRTRate] int ,
	[CurrencyCode] [nvarchar](255) ,
	[Market] [nvarchar](255) ,
	[CriticalPartReportLocationTitle] [nvarchar](255) ,
	[IsMRBWareHouse] [nvarchar](255) ,
	[WeekDayWorkHours] [nvarchar](255) ,
	[IsEngineering] [nvarchar](255) ,
	[PreferredLanguage] [nvarchar](255) ,
	DW_CREATED_DATE	date						DEFAULT getdate(),
	DW_CREATED_BY	varchar(200)				Default suser_sname(),
	DW_UPDATED_DATE	date						DEFAULT getdate(),
	DW_UPDATED_BY	varchar(200)				Default suser_sname()
)